---
# tasks file for roles/oleg.nagios-client
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install Nrpe and plugins
  yum:
    name: "{{ item }}"
    state: latest
  loop: ["nrpe", "nagios-plugins-all"]

  -name: Add nagios server to the list of allow