---
- name: "Chrony server installation"
  hosts: ntpserver
  become: yes
  tasks:
    - name: Update chrony package
      yum:
        name: chrony
        state: latest
    - name: Add ntp service to a firewalld
      firewalld:
        service: ntp
        state: enabled
        permanent: yes
        immediate: yes
    - name: Edit IP range in a config file
      lineinfile:
        path: "/etc/chrony.conf"
        regexp: '^#allow'
        line: 'allow 192.168.1.0/24'
    - name: Edit local stratum in a config file
      lineinfile:
        path: "/etc/chrony.conf"
        regexp: '^#local'
        line: 'local stratum 10'
    - name: Restart the service
      service:
        name: chronyd
        state: restarted

- name: "Setting up chrony client"
  hosts: ntpclient
  become: yes
  tasks:
    - name: Update chrony package
      yum: 
        name: chrony
        state: latest

    - name: Comment out server lines
      lineinfile:
        path: "/etc/chrony.conf"
        regexp: '^server'
        state: absent


    
    - name: Add NTP server IP
      lineinfile:
        path: "/etc/chrony.conf"
        line: 'server 192.168.1.221 iburst'

    - name: Restart the service
      service:
        name: chronyd
        state: restarted     