---
- name: "Installing apache webserver"
  hosts: 192.168.1.222
  vars:
    pckg_name: nginx
    doc_root: "/usr/share/nginx/html"
  become: yes
  tasks:
    - name: Remove index.html file
      file:
        path: "{{ doc_root }}/index.html"
        state: absent
    - name: Remove firewall rule
      firewalld:
        state: disabled
        service: http
        permanent: yes
        immediate: yes
    - name: Stop and disable a service
      service:
        state: stopped
        name: "{{ pckg_name }}"
        enabled: no
    - name: Uninstalling a package
      yum:
        name: "{{ pckg_name }}"
        state: absent
    - name: Uninstall epel-release repo
      yum:
        name: epel-release
        state: absent
      when: pckg_name == "nginx"
