---
- name: "Installing apache webserver"
  hosts: 192.168.1.222
  vars:
    pckg_name: nginx
    html_message: "This is a 1st nginx server we created ever"
    doc_root: "/usr/share/nginx/html"
  become: yes
  tasks:
    - name: Install epel-release repo
      yum:
        name: epel-release
        state: present
      when: pckg_name == "nginx"

    - name: Installing a package
      yum:
        name: "{{ pckg_name }}"
        state: present

    - name: Start and enable a service
      service:
        state: started
        name: "{{ pckg_name }}"
        enabled: yes

    - name: Add firewall rule
      firewalld:
        state: enabled
        service: http
        permanent: yes
        immediate: yes

    - name: Add index.html file
      copy:
        dest: "{{ doc_root }}/index.html"
        content: "{{ html_message }}"
